const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");
const pool = require("../config/db");

/* ── Data fetchers ── */

async function fetchTripReportRows() {
  const [rows] = await pool.query(
    `SELECT tr.trip_id,
            t.truck_no,
            d.name AS driver_name,
            tr.trip_date,
            COALESCE(fd.daily_fuel_cost, 0) AS fuel_cost,
            COALESCE(tr.amount, 0) AS revenue
     FROM trips tr
     LEFT JOIN truck_details t ON tr.truck_id = t.truck_id
     LEFT JOIN driver_details d ON tr.driver_id = d.driver_id
     LEFT JOIN (
       SELECT truck_id, DATE(fuel_date) AS date_only, SUM(price) AS daily_fuel_cost
       FROM fuel_details
       GROUP BY truck_id, DATE(fuel_date)
     ) fd ON fd.truck_id = tr.truck_id AND fd.date_only = DATE(tr.trip_date)
     ORDER BY tr.trip_date DESC, tr.trip_id DESC`
  );
  return rows;
}

async function fetchFuelReportRows() {
  const [rows] = await pool.query(
    `SELECT t.truck_no,
            f.liters AS fuel_amount,
            f.price AS fuel_cost,
            f.fuel_date
     FROM fuel_details f
     LEFT JOIN truck_details t ON f.truck_id = t.truck_id
     ORDER BY f.fuel_date DESC, f.fuel_id DESC`
  );
  return rows;
}

async function fetchMonthlyRevenueRows() {
  const [rows] = await pool.query(
    `SELECT DATE_FORMAT(tr.trip_date, '%Y-%m') AS month,
            COUNT(*) AS trip_count,
            COALESCE(SUM(tr.amount), 0) AS total_revenue
     FROM trips tr
     GROUP BY DATE_FORMAT(tr.trip_date, '%Y-%m')
     ORDER BY month DESC`
  );
  return rows;
}

/* ── Formatting helpers ── */

const MONTH_SHORT = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

// Table cell date: 10/03/2026
function fmtDate(v) {
  if (!v) return "-";
  const d = new Date(v);
  if (isNaN(d)) return String(v);
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  return `${dd}/${mm}/${d.getFullYear()}`;
}

// Header date: 12 Mar 2026
function fmtDateMedium(v) {
  if (!v) return "-";
  const d = new Date(v);
  if (isNaN(d)) return String(v);
  return `${d.getDate()} ${MONTH_SHORT[d.getMonth()]} ${d.getFullYear()}`;
}

// Excel date: 2026-03-10
function fmtDateShort(v) {
  if (!v) return "-";
  const d = new Date(v);
  if (isNaN(d)) return String(v);
  return d.toISOString().split("T")[0];
}

// Indian Rupee: Rs.20,00,000
function fmtINR(v) {
  const n = Number(v || 0);
  return "Rs." + n.toLocaleString("en-IN", { maximumFractionDigits: 0 });
}

// Month label: Mar 2026
function fmtMonth(v) {
  if (!v) return "-";
  const parts = String(v).split("-");
  if (parts.length !== 2) return String(v);
  const mi = Number(parts[1]) - 1;
  if (mi < 0 || mi > 11) return String(v);
  return `${MONTH_SHORT[mi]} ${parts[0]}`;
}

/* ── PDF constants ── */

const PDF_MARGIN    = 50;
const PAGE_WIDTH    = 595.28;
const CONTENT_WIDTH = PAGE_WIDTH - PDF_MARGIN * 2;   // 495.28 pt
const FOOTER_TEXT   = "Generated by TruckBoss Pro Fleet Management System";

const COLORS = {
  primary:      "#1F4E78",
  headerBg:     "#1F4E78",
  headerText:   "#FFFFFF",
  altRow:       "#E8ECF1",
  white:        "#FFFFFF",
  text:         "#333333",
  lightText:    "#666666",
  divider:      "#CCCCCC",
  rowBorder:    "#D0D5DD",
  summaryBg:    "#EAF2FB",
  summaryBorder:"#1F4E78",
  bannerSub:    "#B8D4F0",
  colDivider:   "#4A7EAA",
};

/* ── PDF helpers ── */

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor(COLORS.lightText)
      .text(FOOTER_TEXT, PDF_MARGIN, 780, { width: CONTENT_WIDTH, align: "center" });
    doc.text(`Page ${i + 1} of ${range.count}`, PDF_MARGIN, 792, {
      width: CONTENT_WIDTH,
      align: "center",
    });
  }
}

function writePdfHeader(doc, reportName) {
  const startY = PDF_MARGIN;
  const bannerH = 56;

  // Navy banner
  doc.rect(PDF_MARGIN, startY, CONTENT_WIDTH, bannerH).fill(COLORS.headerBg);

  // Company name (left)
  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor(COLORS.headerText)
    .text("TruckBoss Pro", PDF_MARGIN + 14, startY + 10, {
      width: CONTENT_WIDTH - 28,
      align: "left",
    });

  // Subtitle (left)
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(COLORS.bannerSub)
    .text("Fleet Management System", PDF_MARGIN + 14, startY + 34, {
      width: CONTENT_WIDTH - 28,
      align: "left",
    });

  // Generated date (right)
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(COLORS.bannerSub)
    .text(`Generated: ${fmtDateMedium(new Date())}`, PDF_MARGIN + 14, startY + 10, {
      width: CONTENT_WIDTH - 28,
      align: "right",
    });

  // Advance cursor past banner
  doc.y = startY + bannerH + 14;

  // Report name
  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(COLORS.primary)
    .text(reportName, PDF_MARGIN, doc.y, { width: CONTENT_WIDTH, align: "center" });

  // Underline
  doc.moveDown(0.25);
  const lineY = doc.y;
  doc
    .moveTo(PDF_MARGIN, lineY)
    .lineTo(PAGE_WIDTH - PDF_MARGIN, lineY)
    .strokeColor(COLORS.primary)
    .lineWidth(1)
    .stroke();

  doc.y = lineY + 14;
}

function writeSummarySection(doc, items) {
  // Section heading
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(COLORS.primary)
    .text("REPORT SUMMARY", PDF_MARGIN, doc.y, { width: CONTENT_WIDTH });

  doc.moveDown(0.3);

  // Short accent line
  const accentY = doc.y;
  doc
    .moveTo(PDF_MARGIN, accentY)
    .lineTo(PDF_MARGIN + 100, accentY)
    .strokeColor(COLORS.primary)
    .lineWidth(2)
    .stroke();

  doc.y = accentY + 10;

  // Card grid: 2 columns
  const GAP    = 10;
  const COLS   = 2;
  const CARD_W = (CONTENT_WIDTH - GAP * (COLS - 1)) / COLS;
  const CARD_H = 46;
  const baseY  = doc.y;

  items.forEach((item, idx) => {
    const col   = idx % COLS;
    const row   = Math.floor(idx / COLS);
    const cardX = PDF_MARGIN + col * (CARD_W + GAP);
    const cardY = baseY + row * (CARD_H + 8);

    // Card background + border
    doc
      .roundedRect(cardX, cardY, CARD_W, CARD_H, 4)
      .fillAndStroke(COLORS.summaryBg, COLORS.summaryBorder);

    // Left accent bar
    doc.rect(cardX, cardY, 3, CARD_H).fill(COLORS.primary);

    // Label
    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor(COLORS.lightText)
      .text(item.label, cardX + 12, cardY + 8, { width: CARD_W - 16 });

    // Value
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .fillColor(COLORS.primary)
      .text(item.value, cardX + 12, cardY + 22, { width: CARD_W - 16 });
  });

  const numRows = Math.ceil(items.length / COLS);
  doc.y = baseY + numRows * (CARD_H + 8) + 12;
  doc.font("Helvetica");
}

/* ── Table helpers ── */

function drawTableHeader(doc, columns, y) {
  const ROW_H = 26;

  doc.rect(PDF_MARGIN, y, CONTENT_WIDTH, ROW_H).fill(COLORS.headerBg);

  // Subtle vertical dividers
  columns.slice(0, -1).forEach((col) => {
    const divX = col.x + col.width + (col.gap || 0) / 2;
    doc
      .moveTo(divX, y + 4)
      .lineTo(divX, y + ROW_H - 4)
      .strokeColor(COLORS.colDivider)
      .lineWidth(0.5)
      .stroke();
  });

  // Header labels — 3pt inset
  columns.forEach((col) => {
    doc
      .font("Helvetica-Bold")
      .fontSize(8.5)
      .fillColor(COLORS.headerText)
      .text(col.label, col.x + 3, y + 8, {
        width: col.width - 3,
        align: col.align || "left",
      });
  });

  doc.font("Helvetica");
  return y + ROW_H;
}

function drawTableRow(doc, columns, rowData, y, isAlt) {
  const ROW_H = 22;

  doc
    .rect(PDF_MARGIN, y, CONTENT_WIDTH, ROW_H)
    .fill(isAlt ? COLORS.altRow : COLORS.white);

  doc
    .moveTo(PDF_MARGIN, y + ROW_H)
    .lineTo(PAGE_WIDTH - PDF_MARGIN, y + ROW_H)
    .strokeColor(COLORS.rowBorder)
    .lineWidth(0.3)
    .stroke();

  columns.forEach((col) => {
    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor(COLORS.text)
      .text(String(rowData[col.key] ?? "-"), col.x + 3, y + 7, {
        width: col.width - 3,
        align: col.align || "left",
        ellipsis: true,
        lineBreak: false,
      });
  });

  return y + ROW_H;
}

function ensurePdfPage(doc, y, columns, minBottom = 748) {
  if (y > minBottom) {
    doc.addPage();
    y = drawTableHeader(doc, columns, PDF_MARGIN);
  }
  return y;
}

/* ── Excel helpers ── */

function styleExcelHeader(worksheet) {
  const headerRow = worksheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF1F4E78" },
  };
  headerRow.alignment = { vertical: "middle", horizontal: "center" };
  headerRow.height = 20;
}

function addTotalsRow(worksheet, labelColumnKey, totalsMap) {
  const totalRowData = { [labelColumnKey]: "TOTAL" };
  Object.keys(totalsMap).forEach((key) => {
    totalRowData[key] = totalsMap[key];
  });
  const totalRow = worksheet.addRow(totalRowData);
  totalRow.font = { bold: true };
  totalRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFE2F0D9" },
  };
}

/* ══════════════════════════════════════════
   TRIPS PDF
   ══════════════════════════════════════════ */

async function exportTripsPdf(req, res, next) {
  try {
    const rows = await fetchTripReportRows();

    const totalTrips  = rows.length;
    const totalRevenue  = rows.reduce((s, r) => s + Number(r.revenue  || 0), 0);
    const totalFuelCost = rows.reduce((s, r) => s + Number(r.fuel_cost || 0), 0);
    const avgRevenue  = totalTrips ? totalRevenue / totalTrips : 0;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=trip-report.pdf");

    const doc = new PDFDocument({ margin: PDF_MARGIN, size: "A4", bufferPages: true });
    doc.pipe(res);

    writePdfHeader(doc, "Trips Report");

    writeSummarySection(doc, [
      { label: "Total Trips",              value: String(totalTrips) },
      { label: "Total Revenue",            value: fmtINR(totalRevenue) },
      { label: "Total Fuel Cost",          value: fmtINR(totalFuelCost) },
      { label: "Average Revenue per Trip", value: fmtINR(avgRevenue) },
    ]);

    // Divider before table
    doc
      .moveTo(PDF_MARGIN, doc.y)
      .lineTo(PAGE_WIDTH - PDF_MARGIN, doc.y)
      .strokeColor(COLORS.divider)
      .lineWidth(0.5)
      .stroke();
    doc.moveDown(0.5);

    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor(COLORS.primary)
      .text("Trip Details", PDF_MARGIN, doc.y);
    doc.font("Helvetica").moveDown(0.4);

    // ── Column layout ──────────────────────────────────────────────────────
    // A4 content width = 495pt  (595.28 − 2×50)
    // widths: 34+65+88+78+42+68+72 = 447
    // gaps:   6×8 = 48
    // total:  447+48 = 495 ✓
    // ────────────────────────────────────────────────────────────────────────
    const GAP = 8;
    const columns = [
      { label: "Trip ID",   key: "trip_id",     x: PDF_MARGIN,       width: 34, gap: GAP, align: "left"  },
      { label: "Truck",     key: "truck_no",    x: PDF_MARGIN + 42,  width: 75, gap: GAP, align: "left"  },
      { label: "Driver",    key: "driver_name", x: PDF_MARGIN + 125, width: 98, gap: GAP, align: "left"  },
      { label: "Date",      key: "trip_date",   x: PDF_MARGIN + 231, width: 88, gap: GAP, align: "left"  },
      { label: "Fuel Cost", key: "fuel_cost",   x: PDF_MARGIN + 327, width: 78, gap: GAP, align: "right" },
      { label: "Revenue",   key: "revenue",     x: PDF_MARGIN + 413, width: 82, gap: 0,   align: "right" },
    ];

    let y = drawTableHeader(doc, columns, doc.y);

    rows.forEach((row, i) => {
      y = ensurePdfPage(doc, y, columns);
      y = drawTableRow(
        doc,
        columns,
        {
          trip_id:     row.trip_id,
          truck_no:    row.truck_no    || "-",
          driver_name: row.driver_name || "-",
          trip_date:   fmtDate(row.trip_date),
          fuel_cost:   fmtINR(row.fuel_cost),
          revenue:     fmtINR(row.revenue),
        },
        y,
        i % 2 === 1
      );
    });

    // Bottom border
    doc
      .moveTo(PDF_MARGIN, y)
      .lineTo(PAGE_WIDTH - PDF_MARGIN, y)
      .strokeColor(COLORS.divider)
      .lineWidth(0.5)
      .stroke();

    addFooter(doc);
    doc.end();
  } catch (err) {
    next(err);
  }
}

/* ══════════════════════════════════════════
   TRIPS EXCEL
   ══════════════════════════════════════════ */

async function exportTripsExcel(req, res, next) {
  try {
    const rows = await fetchTripReportRows();

    const workbook  = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Trip Report");

    worksheet.columns = [
      { header: "Trip ID",      key: "trip_id",     width: 12 },
      { header: "Truck Number", key: "truck_no",    width: 18 },
      { header: "Driver Name",  key: "driver_name", width: 22 },
      { header: "Trip Date",    key: "trip_date",   width: 14 },
      { header: "Fuel Cost",    key: "fuel_cost",   width: 14 },
      { header: "Revenue",      key: "revenue",     width: 14 },
    ];

    rows.forEach((row) => {
      worksheet.addRow({
        trip_id:     row.trip_id,
        truck_no:    row.truck_no    || "",
        driver_name: row.driver_name || "",
        trip_date:   fmtDateShort(row.trip_date),
        fuel_cost:   row.fuel_cost,
        revenue:     row.revenue,
      });
    });

    styleExcelHeader(worksheet);

    const totalFuelCost = rows.reduce((sum, r) => sum + Number(r.fuel_cost || 0), 0);
    const totalRevenue  = rows.reduce((sum, r) => sum + Number(r.revenue   || 0), 0);
    addTotalsRow(worksheet, "driver_name", { fuel_cost: totalFuelCost, revenue: totalRevenue });

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=trip-report.xlsx");

    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    next(err);
  }
}

/* ══════════════════════════════════════════
   FUEL EXCEL
   ══════════════════════════════════════════ */

async function exportFuelExcel(req, res, next) {
  try {
    const rows = await fetchFuelReportRows();

    const workbook  = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Fuel Report");

    worksheet.columns = [
      { header: "Truck Number", key: "truck_no",    width: 18 },
      { header: "Fuel Amount",  key: "fuel_amount", width: 14 },
      { header: "Fuel Cost",    key: "fuel_cost",   width: 14 },
      { header: "Date",         key: "fuel_date",   width: 14 },
    ];

    rows.forEach((row) => {
      worksheet.addRow({
        truck_no:    row.truck_no || "",
        fuel_amount: row.fuel_amount,
        fuel_cost:   row.fuel_cost,
        fuel_date:   fmtDateShort(row.fuel_date),
      });
    });

    styleExcelHeader(worksheet);

    const totalFuelAmount = rows.reduce((sum, r) => sum + Number(r.fuel_amount || 0), 0);
    const totalFuelCost   = rows.reduce((sum, r) => sum + Number(r.fuel_cost   || 0), 0);
    addTotalsRow(worksheet, "truck_no", { fuel_amount: totalFuelAmount, fuel_cost: totalFuelCost });

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=fuel-report.xlsx");

    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    next(err);
  }
}

/* ══════════════════════════════════════════
   MONTHLY REVENUE EXCEL
   ══════════════════════════════════════════ */

async function exportMonthlyRevenueExcel(req, res, next) {
  try {
    const rows = await fetchMonthlyRevenueRows();

    const workbook  = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Monthly Revenue");

    worksheet.columns = [
      { header: "Month",         key: "month",         width: 12 },
      { header: "Trip Count",    key: "trip_count",    width: 14 },
      { header: "Total Revenue", key: "total_revenue", width: 16 },
    ];

    rows.forEach((row) => worksheet.addRow(row));
    styleExcelHeader(worksheet);

    const totalTripCount = rows.reduce((sum, r) => sum + Number(r.trip_count    || 0), 0);
    const totalRevenue   = rows.reduce((sum, r) => sum + Number(r.total_revenue || 0), 0);
    addTotalsRow(worksheet, "month", { trip_count: totalTripCount, total_revenue: totalRevenue });

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=monthly-revenue-report.xlsx");

    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    next(err);
  }
}

/* ══════════════════════════════════════════
   MONTHLY REVENUE PDF
   ══════════════════════════════════════════ */

async function exportMonthlyRevenuePdf(req, res, next) {
  try {
    const rows = await fetchMonthlyRevenueRows();

    const totalTrips        = rows.reduce((s, r) => s + Number(r.trip_count    || 0), 0);
    const totalRevenue      = rows.reduce((s, r) => s + Number(r.total_revenue || 0), 0);
    const avgRevenuePerMonth = rows.length ? totalRevenue / rows.length : 0;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=monthly-revenue-report.pdf");

    const doc = new PDFDocument({ margin: PDF_MARGIN, size: "A4", bufferPages: true });
    doc.pipe(res);

    writePdfHeader(doc, "Monthly Revenue Report");

    writeSummarySection(doc, [
      { label: "Months Covered",           value: String(rows.length) },
      { label: "Total Trips",              value: String(totalTrips) },
      { label: "Total Revenue",            value: fmtINR(totalRevenue) },
      { label: "Avg Revenue per Month",    value: fmtINR(avgRevenuePerMonth) },
    ]);

    doc
      .moveTo(PDF_MARGIN, doc.y)
      .lineTo(PAGE_WIDTH - PDF_MARGIN, doc.y)
      .strokeColor(COLORS.divider)
      .lineWidth(0.5)
      .stroke();
    doc.moveDown(0.5);

    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor(COLORS.primary)
      .text("Revenue by Month", PDF_MARGIN, doc.y);
    doc.font("Helvetica").moveDown(0.4);

    // Monthly revenue columns: Month | Trip Count | Total Revenue
    const GAP = 8;
    const columns = [
      { label: "Month",         key: "month",         x: PDF_MARGIN,                    width: 180, gap: GAP, align: "left"   },
      { label: "Trip Count",    key: "trip_count",    x: PDF_MARGIN + 180 + GAP,        width: 120, gap: GAP, align: "center" },
      { label: "Total Revenue", key: "total_revenue", x: PDF_MARGIN + 180 + GAP + 120 + GAP, width: 179, gap: 0, align: "right" },
    ];

    let y = drawTableHeader(doc, columns, doc.y);

    rows.forEach((row, i) => {
      y = ensurePdfPage(doc, y, columns);
      y = drawTableRow(
        doc,
        columns,
        {
          month:         fmtMonth(row.month),
          trip_count:    String(row.trip_count ?? 0),
          total_revenue: fmtINR(row.total_revenue),
        },
        y,
        i % 2 === 1
      );
    });

    doc
      .moveTo(PDF_MARGIN, y)
      .lineTo(PAGE_WIDTH - PDF_MARGIN, y)
      .strokeColor(COLORS.divider)
      .lineWidth(0.5)
      .stroke();

    addFooter(doc);
    doc.end();
  } catch (err) {
    next(err);
  }
}

module.exports = {
  exportTripsPdf,
  exportTripsExcel,
  exportFuelExcel,
  exportMonthlyRevenueExcel,
  exportMonthlyRevenuePdf,
};
